; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
list	p=16f887
INCLUDE	"p16f887.inc"   
;    STATUS	    EQU H'0003'
;    FSR		    EQU H'0004'
;    PORTA	    EQU H'0005'
;    PORTB	    EQU H'0006'
;    PORTC	    EQU H'0007'
;    PORTD	    EQU H'0008'
;    PORTE	    EQU H'0009'
;    PCLATCH	    EQU H'000A'
;    INTCON	    EQU H'000B'
;    TRISB	    EQU H'0086'
;    TRISD	    EQU	H'0088'	 
;_CONFIG1 EQU H'2007'
 
    ; CONFIG1
 ;__config 0xFBF2    3FFA       3FF7                       3FFF
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_OFF & _FCMEN_ON & _LVP_ON
; CONFIG2
 ;__config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
CBLOCK 0X20
 R1
 R2
 R3
 R4
 I
 ENDC

RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED

MAIN_PROG CODE	0x0005                     ; let linker place main program

START
 ;OPERACIONES DE BIT
    CLRF    PORTB
    BSF	    STATUS,5
    ;BCF	    TRISB,2
    MOVLW   0XFF    ;CONFIGURAMOS EL PUERTO B COMO ENTRADA BINARIA.
    MOVWF   TRISB
    CLRF    TRISD
    CLRF    TRISC
    BCF	    STATUS,5
    BSF	    PORTB,2
    BANKSEL ANSELH
    CLRF    ANSELH
    BANKSEL PORTB
    CLRF    PORTD	;PARTE BAJA DE LA CUENTA DE 16 BITS
    CLRF    PORTC	;PARTE ALTA DE LA CUENTA DE 16 BITS
   
    ;FOR(I=0;I<=22;I=I+3)
    CLRF    I
FOR   
    
    MOVF    I,W
    SUBLW   .22
    BTFSS   STATUS,C
    GOTO    END_FOR
    INCF    PORTC,F    ;0--7 OPERACION QUE SE REPITE DENTRO DEL FOR
    MOVF    I,W
    ADDLW   .3
    MOVWF   I
    GOTO    FOR
    
END_FOR
    GOTO $
BUCLE    
    MOVF    PORTB,W
    MOVWF   R1
   
    ;SI 128<PORTD<=255 INCREMENTAR PORTC
    MOVF    PORTD,W
    SUBLW   .128
    BTFSC   STATUS,C
    GOTO    NO_MAYOR128
    MOVF    PORTD,W
    SUBLW   .255
    BTFSS   STATUS,C
    GOTO    NO_MAYOR128 
    CALL    INC_PORTC
    GOTO    INICIO
    
    ;SI 0<PORTD<=128 DECREMENTAR PORTC
    ;MOVF    PORTD,W
    ;BTFSS   STATUS,Z
    ;GOTO    NO_MAYOR0
NO_MAYOR128    
    MOVF    PORTD,W
    SUBLW   .128
    BTFSS   STATUS,C
    GOTO    INICIO
    CALL    DEC_PORTC
    
    
    
    
INICIO    
    ;SE REALIZA OPERACIÓN XOR PARA DETERMINAR SI PORTB ES IGUAL 4
    MOVLW   .4
    XORWF   R1,W
    BTFSS   STATUS,Z
    GOTO    NO_4
    CALL    INCREMENTAR  ;CONTADOR INCREMENTAL
    
NO_4	
    MOVLW   .7
    XORWF   R1,W
    BTFSS   STATUS,Z
    GOTO    BUCLE
    CALL    DECREMENTAR
    GOTO    BUCLE
    
 INCREMENTAR
    MOVLW   .10
    ADDWF   PORTD,F
    
    RETURN    

 DECREMENTAR
    MOVLW   .10
    SUBWF   PORTD,F
    
    RETURN
    
 INC_PORTC
    INCF    PORTC,F
    RETURN
    
 DEC_PORTC  
    DECF    PORTC,F
    RETURN

     GOTO $                          ; loop forever
   

    END