; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
list	p=16f887
INCLUDE	"p16f887.inc"

; CONFIG1
; __config 0xFBF2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_OFF & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

;cristal 8MHz

CBLOCK 0X20
 REG1
 REG2
 REG3
 REG4
 REG5
 REG6
 REG7
 REG8
 FLAG
 LONG  
ENDC
CBLOCK 0X35
 UNIDADES
 DECENAS
 CENTENAS
 MIL
ENDC



RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

MAIN_PROG CODE                      ; let linker place main program

ORG 0X05
 
LIN1	ADDWF	PCL,1
	DT  "LINEA UNO DE PRUEVA"
LIN2	ADDWF	PCL,1
	DT  "LIENA DOS DE PRUEVA"

START


;CONFIGURACIÓN DE PUERTOS C Y E COMO SALIDA
    MOVLW   0XFF
    MOVWF   PORTE
    BANKSEL ANSEL
    CLRF    ANSEL
    CLRF    ANSELH
    BANKSEL TRISE
    CLRF    TRISE
    CLRF    TRISC
    BANKSEL PORTC
    MOVLW   0XFF
    MOVWF   PORTE
    CLRF    PORTC
    CLRF    REG5
    CLRF    REG7
    CALL    RETARDO			;ESTABILIZAR FUENTE
    
    MOVLW   B'00001101'
    CALL    COMAND8				;ACTIVA DISPLAY

    MOVLW   B'00111000'			;COMUNICACION A 8 BITS DOS LINEAS FUENTE 5X7
    CALL    COMAND8	

    MOVLW   B'00000110'			;NO SE DESPLAZA, APUNTADOR SE INCREMENTA CON NUEVA ESCRITURA DE DATO
    CALL    COMAND8	

    MOVLW   B'00000001'			;BORRA Y REGRESA A CERO
    CALL    COMAND8	
    
    MOVLW   B'00011100'			
    CALL    COMAND8	
    
    CLRF    REG7
    
L1:
    MOVF    REG7,W
    CALL    LIN1
    CALL    DATO8
    INCF    REG7
    BTFSS   REG7,4
    GOTO    L1
    
    
    ;MOVLW   "A"
    ;CALL    DATO8
    
    MOVLW   B'11000000'		;APUNTADOR A LINEA 2 POSICION CERO
    CALL    COMAND8
    CLRF    REG7
    
L2:
    MOVF    REG7,W
    CALL    LIN2
    CALL    DATO8
    INCF    REG7
    BTFSS   REG7,4
    GOTO    L2
    
    ;MOVLW   "C"
    ;CALL    DATO8
		
    GOTO	$
    
;.............................................

;------------RUTINA DE ENVIO DE DATOS Y COMANDOS A LCD----
COMAND8	BCF		PORTE,0			;ENVIO DE COMANDO (EL BIT DEL PROTEUS ES EL INVERTIDO DEL DATASHEET)
		GOTO	$+2
DATO8	BSF		PORTE,0			;ENVIO DE DATO
		MOVWF	PORTC
		BSF	PORTE,1			;HABILITA PANTALLA
		CALL	RETLCD
		BCF	PORTE,1			;DESHABILITA PANTALLA
		CALL	RETLCD
		RETURN
;----------------------------------------------------------    
  

;----------RUTINA DE RETARDO---------------
RETARDO		MOVLW	.2
		MOVWF	REG3
DOS		MOVLW	.2
		MOVWF	REG2
UNO		MOVLW	.25
		MOVWF	REG1
		DECFSZ	REG1,1
		GOTO	$-1
		DECFSZ	REG2,1
		GOTO	UNO
		DECFSZ	REG3,1
		GOTO	DOS
		RETURN
;------------------------------------------
;-------------RUTINA DE RETARDO PARA LCD----
RETLCD	MOVLW	.255
		MOVWF	REG8
RETLCD1	NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		DECFSZ	REG8,1
		GOTO	RETLCD1
		RETURN
END